//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechicle_mngmt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicletbl
    {
        [Required]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Displayname { get; set; }
        [Required]
        public string Make { get; set; }
        [Required]
        public string VehicleType { get; set; }
        [Required]
        public string FuelType { get; set; }
        [Required]
        public Nullable<int> VehicleMass { get; set; }
        [Required]
        public Nullable<int> EngineCapacity_cc_ { get; set; }
        [Required]
        public Nullable<double> MaxSpeed { get; set; }
        [Required]
        public Nullable<double> MaxPower { get; set; }
        [Required]
        public Nullable<double> OnRoadPrice { get; set; }
        [Required]
        public string Description { get; set; }
    }
}
